- type: checkboxes
  id: consent
  attributes:
    label: Consent Confirmation
    description: All checkboxes must be checked to submit this issue.
    options:
      - label: I understand that by submitting this issue, I am sharing the information above with the Linkumori project maintainers
        required: true
      - label: I affirm that I previously gave consent through the Linkumori extension reporting page
        required: true
      - label: I understand that this submission constitutes my second confirmation of consent to share this information
        required: true
