name: Issue Report
description: Report a bug or suggest an enhancement for Linkumori
labels: ["needs-triage"]
body:
  - type: textarea
    id: description
    attributes:
      label: Information about extension like settings and preference etc and browser information and version 
      description: "Please provide details about your browser, extension version, and settings"
      placeholder: "Example: Chrome 123.0.4567.89, Linkumori v1.2.3, Dark mode enabled"
    validations:
      required: false
 
  - type: markdown
    attributes:
      value: |
        ## Consent Confirmation
        **All checkboxes below must be checked to submit this issue.**
  
  - type: checkboxes
    id: consent
    attributes:
      label: Mandatory Consent
      description: You must check all boxes to confirm your consent
      options:
        - label: I understand that by submitting this issue, I am sharing the information above with the Linkumori project maintainers
          required: true
        - label: I affirm that I previously gave consent through the Linkumori extension reporting page
          required: true
        - label: I understand that this submission constitutes my second confirmation of consent to share this information
          required: true
  
 
