name: Issue Report
description: Report a bug or suggest an enhancement for Linkumori
title: "[ISSUE] "
labels: ["needs-triage"]
assignees: []
body:
  - type: dropdown
    id: issue_type
    attributes:
      label: Issue Type
      description: Is this a bug report or feature request?
      options:
        - Bug Report
        - Enhancement Request
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## Issue Details
        Please provide information about your bug or enhancement suggestion.

  - type: input
    id: url
    attributes:
      label: URL (for bug reports)
      description: The URL where the issue occurs (if applicable)
      placeholder: "https://example.com"
    validations:
      required: false

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the bug you've encountered or the enhancement you're suggesting
      placeholder: "When I try to... / I would like to see..."
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior (for bugs) / Use Case (for enhancements)
      description: What did you expect to happen, or how would this enhancement benefit users?
      placeholder: "I expected... / This would be useful when..."
    validations:
      required: true

  - type: textarea
    id: additional_info
    attributes:
      label: Additional Information
      description: Any other context, screenshots, or information that might be helpful
      placeholder: "Other details..."
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ## Consent Confirmation
        **All checkboxes below must be checked to submit this issue.**

  - type: checkboxes
    id: consent
    attributes:
      label: Mandatory Consent
      description: You must check all boxes to confirm your consent
      options:
        - label: I understand that by submitting this issue, I am sharing the information above with the Linkumori project maintainers
          required: true
        - label: I affirm that I previously gave consent through the Linkumori extension reporting page
          required: true
        - label: I understand that this submission constitutes my second confirmation of consent to share this information
          required: true

  - type: markdown
    attributes:
      value: |
        ## Technical Information (for bug reports)
        If you're reporting a bug, the following technical information may have been automatically collected by the extension.
