name: Issue Report
description: Report a bug or suggest an enhancement for Linkumori
labels: ["needs-triage"]
body:
  - type: textarea
    id: description
    attributes:
      label: Extension and Browser Information
      description: "Please provide details about your browser, the Linkumori extension version, and any relevant settings or preferences."
      placeholder: "Example: Chrome 123.0.4567.89, Linkumori v1.2.3, Dark mode enabled"
    validations:
      required: false
  
