name: Issue Report
description: Report a bug or suggest an enhancement for Linkumori
title: "[ISSUE] "
labels: ["needs-triage"]
body:
  - type: description
    id: description
    attributes:
      label: Information about extension like settings and preference etc and browser information and version 
      description: ""
      placeholder: ""
    validations:
      required: false
 
  - type: markdown
    attributes:
      value: |
        ## Consent Confirmation
        **All checkboxes below must be checked to submit this issue.**
  
  - type: checkboxes
    id: consent
    attributes:
      label: Mandatory Consent
      description: You must check all boxes to confirm your consent
      options:
        - label: I understand that by submitting this issue, I am sharing the information above with the Linkumori project maintainers
          required: true
        - label: I affirm that I previously gave consent through the Linkumori extension reporting page
          required: true
        - label: I understand that this submission constitutes my second confirmation of consent to share this information
          required: true
  
  - type: markdown
    attributes:
      value: |
        ## Technical Information (for bug reports)
        If you're reporting a bug, the following technical information may have been automatically collected by the extension.
